### ISSUE TITLE
Dataset Drive Link Broken

### ISSUE THREAD

**Issue by mehulhere** [devmehta01/DiPD#1]
The drive link for the dataset is broken. Please update the links.

Thanks.

**Comment by devmehta01** [comment]
Twitter data can no longer be provided publicly. You can use tweepy to write a simple script to extract tweets. Note that you will have to use your twitter API keys to be able to extract it. For the keywords, you can use keywords that belong to events that you want to extract tweets for.

**Comment by devmehta01** [comment]
Twitter data can no longer be provided publicly. You can use tweepy to write a simple script to extract tweets. Note that you will have to use your twitter API keys to be able to extract it. For the keywords, you can use keywords that belong to events that you want to extract tweets for.
